source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'
use_frameworks!

target 'Meetup' do
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
end
